baseURL: "https://nakuz1n.github.io/"
title: Nikita Kuzin
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main: 
      - name: Home
        url: /
        weight: 10
      - name: Notes
        url: /notes/
        weight: 20

params:
    description: "This website hosts Nikita Kuzin's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Nikita Kuzin
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["notes"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    

    socialIcons:
        - name: Email
          url: mailto:nakuzin@asu.edu

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Nikita Kuzin"


markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2